from __future__ import annotations

import hashlib
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .common import project_root, read_yaml, run, state_root, write_json, write_yaml
from .evidence import read_run
from .policy import effective_policy, path_matches, read_policy_config
from .project_validation import run_validation_profile
from .runtime import _append_event
from .security import redact_value


GITHUB_ACTIONS_PATH = Path(".github") / "workflows" / "embraion-enforcement.yml"
_GENERATED_MARKER = "# Generated by EmbrAIon enforcement. Explicit opt-in surface."


def _git_changed_paths(project: Path, base_ref: str) -> list[str]:
    result = run(
        [
            "git",
            "-C",
            str(project),
            "diff",
            "--name-only",
            "--diff-filter=ACMR",
            f"{base_ref}...HEAD",
        ],
        check=False,
    )
    if result.returncode != 0:
        message = (result.stderr or result.stdout or "").strip()
        raise RuntimeError(
            f"Could not compare enforcement base ref '{base_ref}': {message}"
        )
    return sorted(
        {
            line.replace("\\", "/").lstrip("./")
            for line in result.stdout.splitlines()
            if line.strip()
        }
    )


def enforcement_status(project: Path | None = None) -> dict[str, Any]:
    root = project_root(project)
    policy = effective_policy(root)
    config = policy["enforcement"]
    workflow = root / GITHUB_ACTIONS_PATH
    return {
        "schema-version": 1,
        "project": str(root),
        "policy": config,
        "surfaces": {
            "github-actions": {
                "path": GITHUB_ACTIONS_PATH.as_posix(),
                "present": workflow.is_file(),
                "generated": (
                    workflow.is_file()
                    and _GENERATED_MARKER
                    in workflow.read_text(encoding="utf-8", errors="ignore")
                ),
            }
        },
    }


def _enforcement_path(project: Path, evidence_id: str) -> Path:
    return state_root(project) / "enforcement" / f"{evidence_id}.json"


def check_enforcement(
    *,
    base_ref: str,
    project: Path | None = None,
    run_id: str | None = None,
    external_review_gate: bool = False,
) -> dict[str, Any]:
    root = project_root(project)
    policy = effective_policy(root)
    config = policy["enforcement"]

    if not config.get("enabled", False):
        raise RuntimeError(
            "Project enforcement is disabled. Enable an explicit enforcement "
            "surface before using the gate."
        )

    changed_paths = _git_changed_paths(root, base_ref)
    checks: list[dict[str, Any]] = []

    protected = list(policy["sources"].get("protected") or [])
    protected_changes = [
        path for path in changed_paths if path_matches(path, protected)
    ]
    checks.append(
        {
            "id": "protected-sources",
            "status": "failed" if protected_changes else "passed",
            "changed-paths": protected_changes,
        }
    )

    profile = str(config.get("validation-profile") or "").strip()
    if not profile:
        checks.append(
            {
                "id": "validation",
                "status": "failed",
                "reason": "No enforcement validation profile is configured.",
            }
        )
    else:
        validation = run_validation_profile(
            profile,
            project=root,
            run_id=run_id,
            fail_fast=False,
        )
        checks.append(
            {
                "id": "validation",
                "status": (
                    "passed" if validation["status"] == "passed" else "failed"
                ),
                "profile": profile,
                "validation-status": validation["status"],
                "evidence-id": validation["evidence-id"],
                "evidence-path": validation["evidence-path"],
            }
        )

    review_required = bool(config.get("require-review", False))
    if not review_required:
        checks.append({"id": "review", "status": "not-required"})
    elif run_id:
        run_record = read_run(run_id, root)
        review_status = str(run_record.get("review") or "not-required")
        checks.append(
            {
                "id": "review",
                "status": "passed" if review_status == "passed" else "failed",
                "source": "execution-run",
                "run-id": run_id,
                "review": review_status,
            }
        )
    elif external_review_gate:
        checks.append(
            {
                "id": "review",
                "status": "delegated",
                "source": "external-surface",
            }
        )
    else:
        checks.append(
            {
                "id": "review",
                "status": "failed",
                "reason": (
                    "Review is required but no run evidence was supplied. "
                    "Use --run-id or an explicit external review gate."
                ),
            }
        )

    passed = all(
        item["status"] in {"passed", "not-required", "delegated"}
        for item in checks
    )
    evidence_id = f"gate-{uuid.uuid4().hex[:12]}"
    record = redact_value(
        {
            "schema-version": 1,
            "evidence-id": evidence_id,
            "evidence-path": (
                f".embraion/state/enforcement/{evidence_id}.json"
            ),
            "base-ref": base_ref,
            "changed-paths": changed_paths,
            "checks": checks,
            "passed": passed,
            "run-id": run_id,
            "created-utc": datetime.now(timezone.utc).isoformat(),
        }
    )
    write_json(_enforcement_path(root, evidence_id), record)
    _append_event(
        root,
        {
            "event": "enforcement-checked",
            "evidence-id": evidence_id,
            "passed": passed,
            "changed-path-count": len(changed_paths),
            "run-id": run_id,
        },
    )
    return record


def _github_actions_content(
    *,
    version: str,
    require_review: bool,
) -> str:
    review_step = ""
    if require_review:
        review_step = """
      - name: Require approved pull-request review
        if: ${{ !github.event.pull_request.draft }}
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        shell: bash
        run: |
          approvals="$(gh api "repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" \
            --jq 'group_by(.user.login) | map(sort_by(.submitted_at) | last) | map(select(.state == "APPROVED")) | length')"
          if [ "$approvals" -lt 1 ]; then
            echo "EmbrAIon enforcement requires at least one current approved review."
            exit 1
          fi
"""

    return f"""name: EmbrAIon Enforcement

{_GENERATED_MARKER}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  contents: read
  pull-requests: read

jobs:
  enforce:
    name: EmbrAIon enforcement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pinned EmbrAIon
        run: python -m pip install "embraion=={version}"

      - name: Enforce project policy and validation
        run: >-
          embraion enforcement check
          --base-ref "${{ github.event.pull_request.base.sha }}"
          {"--external-review-gate" if require_review else ""}
{review_step}"""


def install_enforcement_surface(
    *,
    surface: str,
    project: Path | None = None,
    validation_profile: str = "affected",
    require_review: bool = False,
    force: bool = False,
) -> dict[str, Any]:
    if surface != "github-actions":
        raise RuntimeError(
            "Unsupported enforcement surface. Supported: github-actions."
        )

    root = project_root(project)
    profiles = effective_policy(root)["validation"]["profiles"]
    if validation_profile not in profiles:
        raise RuntimeError(
            f"Unknown validation profile for enforcement: {validation_profile}"
        )

    manifest = read_yaml(root / ".embraion" / "project.yaml") or {}
    version = str((manifest.get("framework") or {}).get("version") or "").strip()
    if not version:
        raise RuntimeError("Project framework.version is required for CI enforcement.")

    policy_path = root / ".embraion" / "policy.yaml"
    policy = read_policy_config(root)
    policy["enforcement"] = {
        "enabled": True,
        "validation-profile": validation_profile,
        "require-review": require_review,
    }

    workflow = root / GITHUB_ACTIONS_PATH
    content = _github_actions_content(
        version=version,
        require_review=require_review,
    )
    if workflow.exists():
        existing = workflow.read_text(encoding="utf-8")
        if existing != content and not force:
            raise RuntimeError(
                f"{workflow} already exists with different content. "
                "Use --force only when intentional replacement is approved."
            )

    write_yaml(policy_path, policy)
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(content, encoding="utf-8")

    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
    _append_event(
        root,
        {
            "event": "enforcement-surface-installed",
            "surface": surface,
            "path": GITHUB_ACTIONS_PATH.as_posix(),
            "validation-profile": validation_profile,
            "require-review": require_review,
        },
    )
    return {
        "schema-version": 1,
        "surface": surface,
        "path": GITHUB_ACTIONS_PATH.as_posix(),
        "sha256": digest,
        "validation-profile": validation_profile,
        "require-review": require_review,
        "enabled": True,
        "note": (
            "The workflow fails unsafe changes, missing validation, and "
            "configured review requirements. Configure this status check as "
            "required in repository branch rules to make merge blocking mandatory."
        ),
    }
