from __future__ import annotations

import hashlib
import os
import subprocess
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import __version__
from .artifacts import read_framework_pin
from .common import project_root, state_root, write_json, write_yaml
from .environment import child_environment
from .evidence import read_run, review_snapshot
from .policy import (
    effective_policy,
    path_matches,
    read_policy_config,
)
from .project_validation import run_validation_profile
from .protected_sources import (
    BASE_TREE_MODE,
    NAME_MODE,
    PROTECTED_SOURCE_MODES,
    base_policy_mode,
    check_base_tree,
)
from .runtime import _append_event
from .security import redact_value


GITHUB_ACTIONS_PATH = Path(".github") / "workflows" / "embraion-enforcement.yml"
SETUP_ACTION = "GORYNED/EmbrAIon/actions/setup"
_GENERATED_MARKER = "# Generated by EmbrAIon enforcement. Explicit opt-in surface."


def _git_changed_paths(project: Path, base_ref: str) -> list[str]:
    # Binary output avoids newline translation and Git's quoted path syntax.
    def git_paths(command: list[str], *, check: bool = False):
        return subprocess.run(command, check=check, capture_output=True,
                              env=child_environment())

    committed = git_paths(
        [
            "git",
            "-C",
            str(project),
            "diff",
            "--name-only",
            "-z",
            "--no-renames",
            f"{base_ref}...HEAD",
        ],
        check=False,
    )
    if committed.returncode != 0:
        message = (committed.stderr or committed.stdout or "").strip()
        raise RuntimeError(
            f"Could not compare enforcement base ref '{base_ref}': {message}"
        )

    working = git_paths(
        [
            "git",
            "-C",
            str(project),
            "diff",
            "--name-only",
            "-z",
            "--no-renames",
            "HEAD",
        ],
        check=False,
    )
    if working.returncode != 0:
        message = (working.stderr or working.stdout or "").strip()
        raise RuntimeError(f"Could not inspect working tree changes: {message}")

    untracked = git_paths(
        [
            "git",
            "-C",
            str(project),
            "ls-files",
            "-z",
            "--others",
            "--exclude-standard",
        ],
        check=False,
    )
    if untracked.returncode != 0:
        message = (untracked.stderr or untracked.stdout or "").strip()
        raise RuntimeError(f"Could not inspect untracked files: {message}")

    values = (
        committed.stdout.split(b"\0")
        + working.stdout.split(b"\0")
        + untracked.stdout.split(b"\0")
    )
    return sorted(
        {
            os.fsdecode(line)
            for line in values
            if line
        }
    )


def enforcement_status(project: Path | None = None) -> dict[str, Any]:
    root = project_root(project)
    policy = effective_policy(root)
    config = policy["enforcement"]
    workflow = root / GITHUB_ACTIONS_PATH
    return {
        "schema-version": 1,
        "project": str(root),
        "policy": config,
        "surfaces": {
            "github-actions": {
                "path": GITHUB_ACTIONS_PATH.as_posix(),
                "present": workflow.is_file(),
                "generated": (
                    workflow.is_file()
                    and _GENERATED_MARKER
                    in workflow.read_text(encoding="utf-8", errors="ignore")
                ),
            }
        },
    }


def _enforcement_path(project: Path, evidence_id: str) -> Path:
    return state_root(project) / "enforcement" / f"{evidence_id}.json"


def check_enforcement(
    *,
    base_ref: str,
    project: Path | None = None,
    run_id: str | None = None,
    external_review_gate: bool = False,
    protected_sources: str | None = None,
) -> dict[str, Any]:
    root = project_root(project)
    policy = effective_policy(root)
    config = policy["enforcement"]
    # An explicit argument wins so CI can pin the mode independently of the checked-out policy.
    protected_mode = protected_sources or str(config.get("protected-sources") or NAME_MODE)
    if protected_mode not in PROTECTED_SOURCE_MODES:
        raise RuntimeError(
            "Unknown protected-sources mode: "
            f"{protected_mode}. Supported: {', '.join(PROTECTED_SOURCE_MODES)}."
        )

    if not config.get("enabled", False):
        raise RuntimeError(
            "Project enforcement is disabled. Enable an explicit enforcement "
            "surface before using the gate."
        )

    mode_source = None
    if protected_sources is None and protected_mode != BASE_TREE_MODE:
        # The policy at the merge base pins the stricter mode: a change cannot turn it off.
        if base_policy_mode(root, base_ref) == BASE_TREE_MODE:
            protected_mode = BASE_TREE_MODE
            mode_source = "merge-base-policy"

    run_record = read_run(run_id, root) if run_id else None
    if run_record is not None and run_record.get("state") not in {"active", "completed", "blocked", "failed", "cancelled"}:
        raise RuntimeError("Unknown execution run state for enforcement.")
    # A gate owns fresh validation evidence. Completed run evidence is immutable;
    # keep its association on the gate without attaching to the closed run.
    validation_run_id = run_id if run_record and run_record.get("state") == "active" else None
    initial_snapshot = review_snapshot(root)
    changed_paths = _git_changed_paths(root, base_ref)
    checks: list[dict[str, Any]] = []

    protected = list(policy["sources"].get("protected") or [])

    def protected_check(paths: list[str]) -> dict[str, Any]:
        if protected_mode == BASE_TREE_MODE:
            result = check_base_tree(root, base_ref, protected)
            if mode_source:
                result["mode-source"] = mode_source
            return result
        changes = [path for path in paths if path_matches(path, protected)]
        return {
            "id": "protected-sources",
            "status": "failed" if changes else "passed",
            "changed-paths": changes,
        }

    checks.append(protected_check(changed_paths))

    profile = str(config.get("validation-profile") or "").strip()
    if not profile:
        checks.append(
            {
                "id": "validation",
                "status": "failed",
                "reason": "No enforcement validation profile is configured.",
            }
        )
    else:
        validation = run_validation_profile(
            profile,
            project=root,
            run_id=validation_run_id,
            fail_fast=False,
        )
        checks.append(
            {
                "id": "validation",
                "status": (
                    "passed" if validation["status"] == "passed" else "failed"
                ),
                "profile": profile,
                "validation-status": validation["status"],
                "evidence-id": validation["evidence-id"],
                "evidence-path": validation["evidence-path"],
            }
        )

    final_snapshot = review_snapshot(root)
    changed_paths = sorted(set(changed_paths) | set(_git_changed_paths(root, base_ref)))
    checks[0] = protected_check(changed_paths)
    checks.append({
        "id": "workspace-stability",
        "status": "passed" if initial_snapshot and initial_snapshot == final_snapshot else "failed",
        "reason": "Validation must preserve the inspected Git snapshot; unverifiable state fails closed.",
    })

    review_required = bool(config.get("require-review", False))
    if not review_required:
        checks.append({"id": "review", "status": "not-required"})
    elif run_id:
        run_record = read_run(run_id, root)
        review_status = str(run_record.get("review") or "not-required")
        recorded_snapshot = run_record.get("review-snapshot")
        fresh = bool(recorded_snapshot) and recorded_snapshot == initial_snapshot == final_snapshot
        checks.append(
            {
                "id": "review",
                "status": "passed" if review_status == "passed" and fresh else "failed",
                "snapshot-matches": fresh,
                "reason": None if fresh else "Review snapshot is missing, stale, or cannot be verified.",
                "source": "execution-run",
                "run-id": run_id,
                "review": review_status,
            }
        )
    elif external_review_gate:
        checks.append(
            {
                "id": "review",
                "status": "delegated",
                "source": "external-surface",
            }
        )
    else:
        checks.append(
            {
                "id": "review",
                "status": "failed",
                "reason": (
                    "Review is required but no run evidence was supplied. "
                    "Use --run-id or an explicit external review gate."
                ),
            }
        )

    passed = all(
        item["status"] in {"passed", "not-required", "delegated"}
        for item in checks
    )
    evidence_id = f"gate-{uuid.uuid4().hex[:12]}"
    record = redact_value(
        {
            "schema-version": 1,
            "evidence-id": evidence_id,
            "evidence-path": (
                f".embraion/state/enforcement/{evidence_id}.json"
            ),
            "base-ref": base_ref,
            "changed-paths": changed_paths,
            "checks": checks,
            "passed": passed,
            "run-id": run_id,
            "created-utc": datetime.now(timezone.utc).isoformat(),
        }
    )
    write_json(_enforcement_path(root, evidence_id), record)
    _append_event(
        root,
        {
            "event": "enforcement-checked",
            "evidence-id": evidence_id,
            "passed": passed,
            "changed-path-count": len(changed_paths),
            "run-id": run_id,
        },
    )
    return record


def _github_actions_content(
    *,
    action_version: str,
    require_review: bool,
    protected_sources: str | None = None,
) -> str:
    """Reference the setup action; it reads and installs the pin, so pin updates need no edit."""
    review_step = ""
    if require_review:
        review_step = """
      - name: Require approved pull-request review
        if: ${{ !github.event.pull_request.draft }}
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        shell: bash
        run: |
          approvals="$(gh api "repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" |
            jq --arg head "$HEAD_SHA" 'group_by(.user.login) | map(sort_by(.submitted_at) | last) | map(select(.state == "APPROVED" and .commit_id == $head)) | length')"
          if [ "$approvals" -lt 1 ]; then
            echo "EmbrAIon enforcement requires at least one current approved review."
            exit 1
          fi
"""

    # Only a non-default mode adds a flag, so the default workflow text is unchanged.
    protected_flag = (
        f"\n          --protected-sources {protected_sources}"
        if protected_sources == BASE_TREE_MODE
        else ""
    )

    return f"""name: EmbrAIon Enforcement

{_GENERATED_MARKER}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  contents: read
  pull-requests: read

jobs:
  enforce:
    name: EmbrAIon enforcement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request head
        uses: actions/checkout@v4
        with:
          ref: ${{{{ github.event.pull_request.head.sha }}}}
          fetch-depth: 0
          persist-credentials: false

      - name: Install the project-pinned EmbrAIon
        uses: {SETUP_ACTION}@v{action_version}
        with:
          python-version: "3.13"

      - name: Enforce project policy and validation
        run: >-
          embraion enforcement check
          --base-ref "${{{{ github.event.pull_request.base.sha }}}}"
          {"--external-review-gate" if require_review else ""}{protected_flag}
{review_step}"""


def install_enforcement_surface(
    *,
    surface: str,
    project: Path | None = None,
    validation_profile: str = "affected",
    require_review: bool = False,
    force: bool = False,
) -> dict[str, Any]:
    if surface != "github-actions":
        raise RuntimeError(
            "Unsupported enforcement surface. Supported: github-actions."
        )

    root = project_root(project)
    profiles = effective_policy(root)["validation"]["profiles"]
    if validation_profile not in profiles:
        raise RuntimeError(
            f"Unknown validation profile for enforcement: {validation_profile}"
        )

    # The setup action refuses an inexact pin in CI; refuse it here before writing anything.
    read_framework_pin(root / ".embraion" / "project.yaml")

    policy_path = root / ".embraion" / "policy.yaml"
    policy = read_policy_config(root)
    kept_mode = (policy.get("enforcement") or {}).get("protected-sources")
    policy["enforcement"] = {
        "enabled": True,
        "validation-profile": validation_profile,
        "require-review": require_review,
    }
    if kept_mode is not None:
        policy["enforcement"]["protected-sources"] = kept_mode

    workflow = root / GITHUB_ACTIONS_PATH
    content = _github_actions_content(
        action_version=__version__,
        require_review=require_review,
        protected_sources=kept_mode,
    )
    if workflow.exists():
        existing = workflow.read_text(encoding="utf-8")
        if existing != content and not force:
            raise RuntimeError(
                f"{workflow} already exists with different content. "
                "Use --force only when intentional replacement is approved."
            )

    write_yaml(policy_path, policy)
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(content, encoding="utf-8")

    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
    _append_event(
        root,
        {
            "event": "enforcement-surface-installed",
            "surface": surface,
            "path": GITHUB_ACTIONS_PATH.as_posix(),
            "validation-profile": validation_profile,
            "require-review": require_review,
        },
    )
    return {
        "schema-version": 1,
        "surface": surface,
        "path": GITHUB_ACTIONS_PATH.as_posix(),
        "sha256": digest,
        "validation-profile": validation_profile,
        "require-review": require_review,
        "enabled": True,
        "note": (
            "The workflow fails unsafe changes, missing validation, and "
            "configured review requirements. Configure this status check as "
            "required in repository branch rules to make merge blocking mandatory."
        ),
    }
